// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LeaderboardConstants
{
        public const string achievement_own_1000_teleporters = "CgkIm4jPkagREAIQHA"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_plane = "CgkIm4jPkagREAIQNw"; // <GPGSID>
        public const string achievement_own_100_limos = "CgkIm4jPkagREAIQDg"; // <GPGSID>
        public const string achievement_reach_1_septillion_investors = "CgkIm4jPkagREAIQPw"; // <GPGSID>
        public const string achievement_own_5000_buses = "CgkIm4jPkagREAIQIA"; // <GPGSID>
        public const string achievement_upgrade_the_rickshaw = "CgkIm4jPkagREAIQKA"; // <GPGSID>
        public const string achievement_reach_level_100 = "CgkIm4jPkagREAIQUw"; // <GPGSID>
        public const string achievement_own_100_sumbarines = "CgkIm4jPkagREAIQEA"; // <GPGSID>
        public const string achievement_complete_the_game = "CgkIm4jPkagREAIQTg"; // <GPGSID>
        public const string achievement_unlock_captain_h_burg = "CgkIm4jPkagREAIQTQ"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_submarine = "CgkIm4jPkagREAIQOA"; // <GPGSID>
        public const string achievement_own_1000_zeppelins = "CgkIm4jPkagREAIQHQ"; // <GPGSID>
        public const string achievement_own_100_zeppelins = "CgkIm4jPkagREAIQEw"; // <GPGSID>
        public const string achievement_own_1000_shuttles = "CgkIm4jPkagREAIQGw"; // <GPGSID>
        public const string achievement_unlock_din_viesel = "CgkIm4jPkagREAIQRQ"; // <GPGSID>
        public const string achievement_own_100_taxis = "CgkIm4jPkagREAIQCw"; // <GPGSID>
        public const string achievement_own_5000_limos = "CgkIm4jPkagREAIQIg"; // <GPGSID>
        public const string achievement_own_5000_planes = "CgkIm4jPkagREAIQIw"; // <GPGSID>
        public const string achievement_purchase_an_investor_upgrade = "CgkIm4jPkagREAIQQg"; // <GPGSID>
        public const string achievement_your_first_rickshaw = "CgkIm4jPkagREAIQAA"; // <GPGSID>
        public const string achievement_unlock_motto_man = "CgkIm4jPkagREAIQRg"; // <GPGSID>
        public const string leaderboard_bos_billionaire_simulator_2 = "CgkIm4jPkagREAIQYw"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_zeppelin = "CgkIm4jPkagREAIQOw"; // <GPGSID>
        public const string achievement_open_your_daily_reward_for_7_consecutive_days = "CgkIm4jPkagREAIQUA"; // <GPGSID>
        public const string achievement_billionaire = "CgkIm4jPkagREAIQWg"; // <GPGSID>
        public const string achievement_win_at_the_slot_machine_50_times = "CgkIm4jPkagREAIQVw"; // <GPGSID>
        public const string achievement_tredecillionaire = "CgkIm4jPkagREAIQXg"; // <GPGSID>
        public const string leaderboard_level = "CgkIm4jPkagREAIQZA"; // <GPGSID>
        public const string achievement_decillionaire = "CgkIm4jPkagREAIQXQ"; // <GPGSID>
        public const string achievement_own_100_teleporters = "CgkIm4jPkagREAIQEg"; // <GPGSID>
        public const string achievement_upgrade_the_plane = "CgkIm4jPkagREAIQLQ"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_tram = "CgkIm4jPkagREAIQNQ"; // <GPGSID>
        public const string achievement_upgrade_the_shuttle = "CgkIm4jPkagREAIQLw"; // <GPGSID>
        public const string leaderboard_time_played = "CgkIm4jPkagREAIQZQ"; // <GPGSID>
        public const string achievement_unlock_rick_mave = "CgkIm4jPkagREAIQSQ"; // <GPGSID>
        public const string achievement_reset_the_game_and_claim_your_investors = "CgkIm4jPkagREAIQQA"; // <GPGSID>
        public const string achievement_own_100_planes = "CgkIm4jPkagREAIQDw"; // <GPGSID>
        public const string achievement_own_1000_planes = "CgkIm4jPkagREAIQGQ"; // <GPGSID>
        public const string achievement_own_1000_buses = "CgkIm4jPkagREAIQFg"; // <GPGSID>
        public const string achievement_own_5000_zeppelins = "CgkIm4jPkagREAIQJw"; // <GPGSID>
        public const string achievement_your_first_zeppelin = "CgkIm4jPkagREAIQCQ"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_teleporter = "CgkIm4jPkagREAIQOg"; // <GPGSID>
        public const string achievement_own_100_rickshaws = "CgkIm4jPkagREAIQCg"; // <GPGSID>
        public const string achievement_own_100_shuttles = "CgkIm4jPkagREAIQEQ"; // <GPGSID>
        public const string achievement_upgrade_the_zeppelin = "CgkIm4jPkagREAIQMQ"; // <GPGSID>
        public const string achievement_purchase_all_available_investor_upgrades = "CgkIm4jPkagREAIQQw"; // <GPGSID>
        public const string achievement_unlock_marvin = "CgkIm4jPkagREAIQTA"; // <GPGSID>
        public const string achievement_own_1000_rickshaws = "CgkIm4jPkagREAIQFA"; // <GPGSID>
        public const string achievement_unlock_nu_clear_jim = "CgkIm4jPkagREAIQSg"; // <GPGSID>
        public const string achievement_own_1000_taxis = "CgkIm4jPkagREAIQFQ"; // <GPGSID>
        public const string achievement_toomuchonaire = "CgkIm4jPkagREAIQYQ"; // <GPGSID>
        public const string achievement_your_first_limo = "CgkIm4jPkagREAIQBA"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_limo = "CgkIm4jPkagREAIQNg"; // <GPGSID>
        public const string achievement_your_first_shuttle = "CgkIm4jPkagREAIQBw"; // <GPGSID>
        public const string achievement_unlock_ricardo_suave = "CgkIm4jPkagREAIQSA"; // <GPGSID>
        public const string achievement_upgrade_the_teleporter = "CgkIm4jPkagREAIQMA"; // <GPGSID>
        public const string achievement_upgrade_the_limo = "CgkIm4jPkagREAIQLA"; // <GPGSID>
        public const string achievement_your_first_plane = "CgkIm4jPkagREAIQBQ"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_rickshaw = "CgkIm4jPkagREAIQMg"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_shuttle = "CgkIm4jPkagREAIQOQ"; // <GPGSID>
        public const string achievement_reset_the_game_and_claim_your_investors_20_times = "CgkIm4jPkagREAIQQQ"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_taxi = "CgkIm4jPkagREAIQMw"; // <GPGSID>
        public const string achievement_reach_level_50 = "CgkIm4jPkagREAIQUg"; // <GPGSID>
        public const string achievement_win_at_the_slot_machine_100_times = "CgkIm4jPkagREAIQWA"; // <GPGSID>
        public const string achievement_reach_1_million_investors = "CgkIm4jPkagREAIQPA"; // <GPGSID>
        public const string achievement_unlock_tom_tanks = "CgkIm4jPkagREAIQRw"; // <GPGSID>
        public const string achievement_novemdecillionaire = "CgkIm4jPkagREAIQYA"; // <GPGSID>
        public const string achievement_own_5000_rickshaws = "CgkIm4jPkagREAIQHg"; // <GPGSID>
        public const string achievement_unlock_wheeliam = "CgkIm4jPkagREAIQRA"; // <GPGSID>
        public const string achievement_own_100_buses = "CgkIm4jPkagREAIQDA"; // <GPGSID>
        public const string achievement_upgrade_the_tram = "CgkIm4jPkagREAIQKw"; // <GPGSID>
        public const string achievement_own_1000_limos = "CgkIm4jPkagREAIQGA"; // <GPGSID>
        public const string achievement_millionaire = "CgkIm4jPkagREAIQWQ"; // <GPGSID>
        public const string achievement_upgrade_the_submarine = "CgkIm4jPkagREAIQLg"; // <GPGSID>
        public const string achievement_level_up = "CgkIm4jPkagREAIQUQ"; // <GPGSID>
        public const string achievement_own_5000_trams = "CgkIm4jPkagREAIQIQ"; // <GPGSID>
        public const string achievement_quintillionaire = "CgkIm4jPkagREAIQXA"; // <GPGSID>
        public const string achievement_your_first_teleporter = "CgkIm4jPkagREAIQCA"; // <GPGSID>
        public const string achievement_win_at_the_slot_machine_10_times = "CgkIm4jPkagREAIQVQ"; // <GPGSID>
        public const string achievement_your_first_tram = "CgkIm4jPkagREAIQAw"; // <GPGSID>
        public const string achievement_own_1000_trams = "CgkIm4jPkagREAIQFw"; // <GPGSID>
        public const string achievement_septendecillionaire = "CgkIm4jPkagREAIQXw"; // <GPGSID>
        public const string achievement_win_at_the_slot_machine_20_times = "CgkIm4jPkagREAIQVg"; // <GPGSID>
        public const string achievement_your_first_submarine = "CgkIm4jPkagREAIQBg"; // <GPGSID>
        public const string achievement_unlock_all_the_upgrades_for_the_bus = "CgkIm4jPkagREAIQNA"; // <GPGSID>
        public const string achievement_open_your_daily_reward = "CgkIm4jPkagREAIQTw"; // <GPGSID>
        public const string achievement_upgrade_the_bus = "CgkIm4jPkagREAIQKg"; // <GPGSID>
        public const string achievement_win_at_the_slot_machine = "CgkIm4jPkagREAIQVA"; // <GPGSID>
        public const string achievement_own_5000_taxis = "CgkIm4jPkagREAIQHw"; // <GPGSID>
        public const string achievement_your_first_bus = "CgkIm4jPkagREAIQAg"; // <GPGSID>
        public const string achievement_own_5000_teleporters = "CgkIm4jPkagREAIQJg"; // <GPGSID>
        public const string achievement_quadrillionaire = "CgkIm4jPkagREAIQWw"; // <GPGSID>
        public const string achievement_own_5000_submarines = "CgkIm4jPkagREAIQJA"; // <GPGSID>
        public const string achievement_own_1000_submarines = "CgkIm4jPkagREAIQGg"; // <GPGSID>
        public const string achievement_reach_1_quadrillion_investors = "CgkIm4jPkagREAIQPQ"; // <GPGSID>
        public const string achievement_unlock_captain_bames_t_cork = "CgkIm4jPkagREAIQSw"; // <GPGSID>
        public const string achievement_own_100_trams = "CgkIm4jPkagREAIQDQ"; // <GPGSID>
        public const string achievement_own_5000_shuttles = "CgkIm4jPkagREAIQJQ"; // <GPGSID>
        public const string achievement_upgrade_the_taxi = "CgkIm4jPkagREAIQKQ"; // <GPGSID>
        public const string achievement_your_first_taxi = "CgkIm4jPkagREAIQAQ"; // <GPGSID>

}

